### ISSUE TITLE
Crash for unusual license identifier

### ISSUE THREAD

**Issue by tenzap** [doubleopen-project/spdx-rs#18]
For a license id like "urn:dje:license:bitstream" there is this crash.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse("urn:dje:license:bitstream")', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/spdx-rs-0.5.0/src/parsers/mod.rs:470:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1098:23
   4: spdx_rs::parsers::process_atom_for_files
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/spdx-rs-0.5.0/src/parsers/mod.rs:470:27
   5: spdx_rs::parsers::spdx_from_atoms
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/spdx-rs-0.5.0/src/parsers/mod.rs:118:9
   6: spdx_rs::parsers::spdx_from_tag_value
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/spdx-rs-0.5.0/src/parsers/mod.rs:72:16
   7: main::main
             at /home/username/spdx-to-dep5/src/bin/main.rs:31:15
   8: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
```

**Comment by tenzap** [comment]
There are also issues for example with a license named `_UNKNOWN_`
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Nom("Parsing Error: Error { input: \"_UNKNOWN_\", code: TakeWhile1 }")', /home/xxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/spdx-rs-0.5.0/src/parsers/mod.rs:470:58
```
